# Generated by Django 3.2 on 2021-07-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='procurement_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
