# Generated by Django 3.2 on 2021-07-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210715_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='procurement_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
