# Generated by Django 3.2 on 2021-07-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210717_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_charge',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='risk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
